brandList: list = [
    { 'title': 'BMW', 'id': 0 },
    { 'title': 'Ford', 'id': 1 },
    { 'title': 'Audi', 'id': 2 },
    { 'title': 'Dodge', 'id': 3 },
    { 'title': 'Reno', 'id': 4 },
    { 'title': 'Volvo', 'id': 5 },
    { 'title': 'Mazda', 'id': 6 },
    { 'title': 'Porshe', 'id': 7 },
    { 'title': 'Lamborgini', 'id': 8 },
    { 'title': 'Lada', 'id': 9 },
    { 'title': 'Opel', 'id': 10 },
    { 'title': 'Chevrole', 'id': 11 },
    { 'title': 'VolzWagen', 'id': 12 },
    { 'title': 'Kia', 'id': 13 },
]

priceList: list = [
    { 'title': '0 - 1k', 'id': 0 },
    { 'title': '1k - 2k', 'id': 1 },
    { 'title': '2k - 3k', 'id': 2 },
    { 'title': '3k - 4k', 'id': 3 },
    { 'title': '4k - 5k', 'id': 4 },
    { 'title': '5k - 6k', 'id': 5 },
    { 'title': '6k - 7k', 'id': 6 },
    { 'title': '7k - 8k', 'id': 7 },
    { 'title': '9k - 10k', 'id': 8 },
    { 'title': '10k - 15k', 'id': 9 },
    { 'title': '15k - 20k', 'id': 10 },
    { 'title': '20k - 25k', 'id': 11 },
    { 'title': '25k - 30k', 'id': 12 },
    { 'title': '30k - 35k', 'id': 13 },
    { 'title': '35k - 40k', 'id': 14 },
    { 'title': '40k - 45k', 'id': 15 },
    { 'title': '45k - 50k', 'id': 16 },
    { 'title': '50k - 1m', 'id': 17 },
]
